-- =====================================================
-- StreamForge Phase 6 - Converted PostgreSQL Schema
-- Automatically converted from Oracle by AWS SCT
-- Manual remediation applied where needed
-- =====================================================

-- REGIONS Table
CREATE TABLE regions (
    region_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    region_name VARCHAR(100) NOT NULL,
    region_code VARCHAR(10) UNIQUE NOT NULL,
    country VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_regions_code ON regions(region_code);

COMMENT ON TABLE regions IS 'Geographic regions for business operations';

-- CUSTOMERS Table
CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    customer_name VARCHAR(200) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    address VARCHAR(500),
    city VARCHAR(100),
    postal_code VARCHAR(20),
    region_id BIGINT,
    customer_status VARCHAR(20) DEFAULT 'ACTIVE',
    credit_limit NUMERIC(12,2) DEFAULT 5000.00,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_date TIMESTAMP,
    notes TEXT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_region FOREIGN KEY (region_id) REFERENCES regions(region_id),
    CONSTRAINT chk_customer_status CHECK (customer_status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE INDEX idx_customers_email ON customers(email);
CREATE INDEX idx_customers_region ON customers(region_id);
CREATE INDEX idx_customers_status ON customers(customer_status);

COMMENT ON TABLE customers IS 'Customer master data';

-- SUPPLIERS Table
CREATE TABLE suppliers (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000) PRIMARY KEY,
    supplier_name VARCHAR(200) NOT NULL,
    contact_name VARCHAR(100),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    address VARCHAR(500),
    city VARCHAR(100),
    postal_code VARCHAR(20),
    region_id BIGINT,
    supplier_status VARCHAR(20) DEFAULT 'ACTIVE',
    payment_terms VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_suppliers_region FOREIGN KEY (region_id) REFERENCES regions(region_id),
    CONSTRAINT chk_supplier_status CHECK (supplier_status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_suppliers_email ON suppliers(email);
CREATE INDEX idx_suppliers_region ON suppliers(region_id);

COMMENT ON TABLE suppliers IS 'Supplier master data';

-- PRODUCTS Table
CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5000) PRIMARY KEY,
    product_name VARCHAR(200) NOT NULL,
    product_code VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    category VARCHAR(100),
    supplier_id BIGINT,
    unit_price NUMERIC(10,2) NOT NULL,
    cost_price NUMERIC(10,2),
    stock_quantity INTEGER DEFAULT 0,
    reorder_level INTEGER DEFAULT 10,
    discontinued CHAR(1) DEFAULT 'N',
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
    CONSTRAINT chk_unit_price CHECK (unit_price >= 0),
    CONSTRAINT chk_discontinued CHECK (discontinued IN ('Y', 'N'))
);

CREATE INDEX idx_products_code ON products(product_code);
CREATE INDEX idx_products_supplier ON products(supplier_id);
CREATE INDEX idx_products_category ON products(category);

COMMENT ON TABLE products IS 'Product catalog';

-- INVENTORY Table
CREATE TABLE inventory (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    product_id BIGINT NOT NULL,
    warehouse_location VARCHAR(100),
    quantity_on_hand INTEGER DEFAULT 0,
    quantity_reserved INTEGER DEFAULT 0,
    quantity_available INTEGER DEFAULT 0,
    last_stock_check_date TIMESTAMP,
    bin_location VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT chk_quantities CHECK (quantity_on_hand >= 0 AND quantity_reserved >= 0)
);

CREATE INDEX idx_inventory_product ON inventory(product_id);

COMMENT ON TABLE inventory IS 'Product inventory tracking';

-- EMPLOYEES Table
CREATE TABLE employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3000) PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    hire_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    job_title VARCHAR(100),
    department VARCHAR(100),
    manager_id BIGINT,
    salary NUMERIC(10,2),
    commission_pct NUMERIC(3,2),
    employee_status VARCHAR(20) DEFAULT 'ACTIVE',
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employees_manager FOREIGN KEY (manager_id) REFERENCES employees(employee_id),
    CONSTRAINT chk_employee_status CHECK (employee_status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE'))
);

CREATE INDEX idx_employees_email ON employees(email);
CREATE INDEX idx_employees_manager ON employees(manager_id);
CREATE INDEX idx_employees_dept ON employees(department);

COMMENT ON TABLE employees IS 'Employee master data';

-- ORDERS Table
CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 20000) PRIMARY KEY,
    order_number VARCHAR(50) UNIQUE NOT NULL,
    customer_id BIGINT NOT NULL,
    employee_id BIGINT,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    required_date TIMESTAMP,
    shipped_date TIMESTAMP,
    order_status VARCHAR(20) DEFAULT 'PENDING',
    order_total NUMERIC(12,2) DEFAULT 0,
    tax_amount NUMERIC(12,2) DEFAULT 0,
    shipping_cost NUMERIC(10,2) DEFAULT 0,
    payment_method VARCHAR(50),
    shipping_address VARCHAR(500),
    billing_address VARCHAR(500),
    notes TEXT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_orders_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
    CONSTRAINT chk_order_status CHECK (order_status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
);

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_employee ON orders(employee_id);
CREATE INDEX idx_orders_status ON orders(order_status);
CREATE INDEX idx_orders_date ON orders(order_date);

COMMENT ON TABLE orders IS 'Sales orders';

-- ORDER_ITEMS Table
CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 50000) PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    discount_pct NUMERIC(5,2) DEFAULT 0,
    line_total NUMERIC(12,2),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT chk_quantity CHECK (quantity > 0),
    CONSTRAINT chk_unit_price CHECK (unit_price >= 0)
);

CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);

COMMENT ON TABLE order_items IS 'Line items for sales orders';

-- PAYMENTS Table
CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 30000) PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_amount NUMERIC(12,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    transaction_id VARCHAR(100) UNIQUE,
    payment_status VARCHAR(20) DEFAULT 'PENDING',
    processor_response TEXT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT chk_payment_amount CHECK (payment_amount >= 0),
    CONSTRAINT chk_payment_status CHECK (payment_status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED'))
);

CREATE INDEX idx_payments_order ON payments(order_id);
CREATE INDEX idx_payments_status ON payments(payment_status);
CREATE INDEX idx_payments_date ON payments(payment_date);

COMMENT ON TABLE payments IS 'Payment transactions';

-- SHIPMENTS Table
CREATE TABLE shipments (
    shipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 40000) PRIMARY KEY,
    order_id BIGINT NOT NULL,
    tracking_number VARCHAR(100) UNIQUE,
    carrier VARCHAR(100),
    shipment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estimated_delivery_date TIMESTAMP,
    actual_delivery_date TIMESTAMP,
    shipment_status VARCHAR(20) DEFAULT 'PREPARING',
    shipping_cost NUMERIC(10,2),
    weight_kg NUMERIC(8,2),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT chk_shipment_status CHECK (shipment_status IN ('PREPARING', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED'))
);

CREATE INDEX idx_shipments_order ON shipments(order_id);
CREATE INDEX idx_shipments_tracking ON shipments(tracking_number);
CREATE INDEX idx_shipments_status ON shipments(shipment_status);

COMMENT ON TABLE shipments IS 'Shipment tracking data';

-- Triggers for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_updated_date()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER regions_update_timestamp
BEFORE UPDATE ON regions
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER customers_update_timestamp
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER suppliers_update_timestamp
BEFORE UPDATE ON suppliers
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER products_update_timestamp
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER inventory_update_timestamp
BEFORE UPDATE ON inventory
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER employees_update_timestamp
BEFORE UPDATE ON employees
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER orders_update_timestamp
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER payments_update_timestamp
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

CREATE TRIGGER shipments_update_timestamp
BEFORE UPDATE ON shipments
FOR EACH ROW
EXECUTE FUNCTION update_updated_date();

-- Trigger for inventory quantity calculation
CREATE OR REPLACE FUNCTION calculate_inventory_available()
RETURNS TRIGGER AS $$
BEGIN
    NEW.quantity_available := NEW.quantity_on_hand - COALESCE(NEW.quantity_reserved, 0);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER inventory_calculate_available
BEFORE INSERT OR UPDATE ON inventory
FOR EACH ROW
EXECUTE FUNCTION calculate_inventory_available();

-- Trigger for order_items line total calculation
CREATE OR REPLACE FUNCTION calculate_order_item_total()
RETURNS TRIGGER AS $$
BEGIN
    NEW.line_total := NEW.quantity * NEW.unit_price * (1 - COALESCE(NEW.discount_pct, 0) / 100);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER order_items_calculate_total
BEFORE INSERT OR UPDATE ON order_items
FOR EACH ROW
EXECUTE FUNCTION calculate_order_item_total();

-- Grant permissions (adjust schema/role as needed)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO migration_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO migration_user;
